module.exports = {
  "ALIVE_IMG": "https://telegra.ph/file/ef48cc8d2d26081f7d46a.jpg",
  "FOOT": "©𝐌𝐑 𝐌𝐀𝐍𝐔𝐋 𝐎𝐅𝐂 💚",
  "PREFIX": ".",
  "SESSION_ID": "put your session id here",
  "AUTO_READ_STATUS": "true",
  "MODE": "public",
  "BOT_NUMBER": "94752902163",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "true",
  "AUTO_VOICE": "true",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "true",
  "ANTI_CALL": "true",
  "ANTI_LINK": "true",
  "ANTI_PHOTO": "true",
  "ANTI_STICKER": "true",nilaweeramanula@gmail.com
  "ALWAYS_ONLINE": "true",
  "MOROCCO_BLOCK": "true",
  "OWNER_NAME": "Manul Official",
  "OWNER_NUMBER": "94752902163",
  "AUTO_BIO": "true",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "true",
  "WARN_COUNT": "3",
};
